### ISSUE TITLE
Missing Translation Keys

### ISSUE THREAD

**Issue by suerion** [sythatic/ModernMetro#2]
Hey, i had used your Mod and come here fore the issue i had found.

In your mod there are missing some translation keys, after adding your mod, it messing with the server console.

should be like this
Preparing spawn area: 2%

but is this
[23:12:13] [Worker-Main-4/INFO]: menu.preparingSpawn

Hope you could fix it :)

Fabric 1.21.1

some other devs, said, that this is an server sides isues with language file. the server side could not merge with client and on server side.

**Comment by suerion** [comment]
Had also found this issue on fabric github 

https://github.com/FabricMC/fabric/issues/2943


Fabric Discord
https://discord.com/channels/507304429255393322/566276937035546624/1297750020589748265

**Comment by samuelh2005** [comment]
This mod does not touch the `menu.preparingSpawn` key at all. There must be another mod casuing the issue, or an internal Fabric / Minecraft bug. The issue https://github.com/FabricMC/fabric/issues/2943 is not related to this bug.

Without your full logs we will not know the true issue.

**Comment by suerion** [comment]
Hey sorry had this not seen anymore, the issue was only persistent on Vanilla Blocks and Modded Blocks on Vanilla Id.

Is fixed on an API update

https://modrinth.com/mod/fabric-api/version/0.107.0+1.21.1

Does fix the issue with the language keys. 

@ajh123 thanks for looking on this
